CREATE TABLE users (id INT AUTO_INCREMENT PRIMARY KEY, email VARCHAR(255) NOT NULL UNIQUE, name VARCHAR(255));
CREATE TABLE products (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255) NOT NULL, price FLOAT NOT NULL, description TEXT);

CREATE TABLE motorvehicles(id INT PRIMARY KEY, Name VARCHAR(255), Price FLOAT);
CREATE TABLE motorbikes(id INT NOT NULL, name VARCHAR(20) NOT NULL, price FLOAT);

SELECT SUM(amount) FROM payments)